root directory src/
output directory dist/
archive dist/ webroot

minify file index.html
minify file main.css
minify directory ict
copy file projects_info.json
copy file sitemap.xml
copy directory projects
copy directory img